stages:
  - deploy

deploy:
  stage: deploy
  script:
    - "cd /home/sites/kriekon.com/frontend"
    - "sudo git pull"
    - "sudo npm update"
    - "sudo npm run build"
    - "sudo rm -rf /home/sites/kriekon.com/frontend/old_dist/*"
    - "sudo cp -R /home/sites/kriekon.com/frontend/www.kriekon.com /home/sites/kriekon.com/frontend/old_dist"
    - "sudo rm -rf /home/sites/kriekon.com/frontend/www.kriekon.com/*"
    - "sudo cp -R /home/sites/kriekon.com/frontend/dist /home/sites/kriekon.com/frontend/www.kriekon.com"
  only:
    - master